JDP190601-18
interceptor2048/project-jdp-1906-01 pull request #18
Opened 2019-07-06 18:35 UTC by majic1985

2019-07-07 12:06 UTC, AnnaSzczech approved these changes

2019-07-07 19:35 UTC, AdamKaczorowski approved these changes

2019-07-09 15:36 UTC, interceptor2048 requested changes

2019-07-09 15:36 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommerce/domain/dto/GroupDto.java
> +    private String group_name;
Stosujemy notację upperCamelCase do nazw zmiennych - nie stosujemy KebabCase (czyli notacji z podkreśleniami).

2019-07-09 15:36 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommerce/service/GroupDbService.java
> +
Zbędne puste linie

2019-07-09 15:48 UTC, AnnaSzczech commented on src/main/java/com/kodilla/ecommerce/domain/dto/GroupDto.java
> +    private String group_name;
a to ja wprowadziłam w błąd w takim razie  -> bo wydawało mi się że jako posługujemy się JSON to zmienne które będą wyświetlane właśni w JSON zwykle widziałam zapisywane w KebabCase

2019-07-14 14:16 UTC, merged