ProductController - initial implementation of endpoints
interceptor2048/project-jdp-1906-01 pull request #2
Opened 2019-06-20 15:58 UTC by AnnaSzczech

2019-06-20 17:30 UTC, adrianpaz requested changes

2019-06-20 17:30 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto updateProduct(ProductDto product){
Brak RequestBody

2019-06-20 17:30 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void Product(Long productId){}
Brak RequestParam

2019-06-20 20:15 UTC, interceptor2048 requested changes

2019-06-20 20:15 UTC, interceptor2048 commented on build.gradle
> +    annotationProcessor('org.projectlombok:lombok:1.18.8')
Nie wskazuj konkretnej wersji - zrób jak powyżej przy `compile`

2019-06-20 20:15 UTC, interceptor2048 commented on build.gradle
> +    compile('mysql:mysql-connector-java')
Jeszcze nie było uzgodnienia, że używamy MySQL :) Ale dla mnie ok - zaproponuj to po prostu pozostałym osobom w zespole na kanale projektu.

2019-06-21 08:14 UTC, interceptor2048 approved these changes

2019-06-22 09:39 UTC, adrianpaz approved these changes

2019-06-22 09:42 UTC, merged